export const PICTURE_LIST_REQUEST = 'PICTURE_LIST_REQUEST';
export const PICTURE_LIST_SUCCESS = 'PICTURE_LIST_SUCCESS';
export const PICTURE_LIST_FAILED = 'PICTURE_LIST_FAILED';

export const PICTURE_DELETE_REQUEST = 'PICTURE_DELETE_REQUEST';
export const PICTURE_DELETE_SUCCESS = 'PICTURE_DELETE_SUCCESS';
export const PICTURE_DELETE_FAILED = 'PICTURE_DELETE_FAILED';

export const PICTURE_CREATE_REQUEST = 'PICTURE_CREATE_REQUEST';
export const PICTURE_CREATE_SUCCESS = 'PICTURE_CREATE_SUCCESS';
export const PICTURE_CREATE_FAILED = 'PICTURE_CREATE_FAILED';
export const PICTURE_CREATE_RESET = 'PICTURE_CREATE_RESET';

export const PICTURE_UPDATE_REQUEST = 'PICTURE_UPDATE_REQUEST';
export const PICTURE_UPDATE_SUCCESS = 'PICTURE_UPDATE_SUCCESS';
export const PICTURE_UPDATE_FAILED = 'PICTURE_UPDATE_FAILED';
export const PICTURE_UPDATE_RESET = 'PICTURE_UPDATE_RESET';
